#!/usr/bin/env bash
# Build the mnemosyne single-binary distribution via PyOxidizer.
#
# Target: linux-x86_64 only (ISSUE-0008 / SPEC-PACKAGE-001 T5).
# Cross-platform matrix, install.sh, and CI are ISSUE-0009 (PACKAGE-D).
#
# Pipeline (T1 POC + T5 base binary, REQ-PKG-001):
#   1. Verify toolchain (pyoxidizer, cargo/rustc, maturin, python3.10).
#   2. Build mnemosyne-core Rust extension via maturin for CPython 3.10
#      (PyOxidizer 0.24 ships a 3.10.9 distribution; see pyoxidizer.bzl
#      CPython version deviation note).
#   3. Create a venv at mnemosyne-core/build_venv with the runtime deps from
#      requirements-binary.txt. PyOxidizer consumes this via read_virtualenv.
#   4. Generate fs_files.star enumerating data files of FILESYSTEM_PACKAGES
#      (jsonschema_specifications, referencing) — frozen-import workaround.
#   5. pyoxidizer build --target-triple x86_64-unknown-linux-gnu (release).
#   6. Copy the stripped binary to build/mnemosyne. Print size (AC6).
#
# Usage:
#   scripts/build_binary.sh            # build + copy + size report
#   scripts/build_binary.sh --check    # only verify toolchain availability
#   scripts/build_binary.sh --debug    # build debug (faster, larger binary)
#
# Environment:
#   PYOXIDIZER_VERSION  (default: 0.24.0; see pin comment in pyoxidizer.bzl)
#   PYTHON_VERSION      (default: 3.10; PyOxidizer 0.24 constraint)
set -euo pipefail

PYTHON_VERSION="${PYTHON_VERSION:-3.10}"
PYOXIDIZER_VERSION="${PYOXIDIZER_VERSION:-0.24.0}"
BUILD_MODE="${BUILD_MODE:-release}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${REPO_ROOT}/build"
VENV_DIR="${REPO_ROOT}/mnemosyne-core/build_venv"
WHEELS_DIR="${REPO_ROOT}/mnemosyne-core/target/wheels"

err() { printf 'build_binary.sh: ERROR: %s\n' "$*" >&2; }
log() { printf 'build_binary.sh: %s\n' "$*"; }

check_toolchain() {
    local missing=0
    for tool in pyoxidizer cargo rustc maturin; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            err "missing required tool: $tool"
            missing=1
        fi
    done
    # Locate python3.10 via uv (preferred) or system PATH.
    local py_bin
    py_bin="$(command -v python${PYTHON_VERSION} || true)"
    if [[ -z "$py_bin" ]] && command -v uv >/dev/null 2>&1; then
        py_bin="$(uv python find "${PYTHON_VERSION}" 2>/dev/null || true)"
    fi
    if [[ -z "$py_bin" ]]; then
        err "missing required interpreter: python${PYTHON_VERSION}"
        err "install via: uv python install ${PYTHON_VERSION}"
        missing=1
    fi
    if [[ "$missing" -ne 0 ]]; then
        cat >&2 <<EOF

To install the toolchain (outside ISSUE-0008 scope — recorded for repro):

  # Rust + maturin (PyO3 build of mnemosyne-core)
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source "\$HOME/.cargo/env"
  pip install maturin

  # Python 3.10 (PyOxidizer 0.24 constraint)
  uv python install ${PYTHON_VERSION}

  # PyOxidizer (pin: see pyoxidizer.bzl)
  pip install pyoxidizer==${PYOXIDIZER_VERSION}

Re-run this script after the toolchain is on PATH.
EOF
        return 1
    fi
    log "toolchain OK (pyoxidizer $(pyoxidizer --version 2>&1 | head -1), python${PYTHON_VERSION} at ${py_bin})"
    return 0
}

build_rust_extension() {
    log "building mnemosyne-core via maturin (target: cpython-${PYTHON_VERSION}-x86_64-linux-gnu)"
    mkdir -p "${WHEELS_DIR}"
    local py_bin
    py_bin="$(command -v python${PYTHON_VERSION} || uv python find "${PYTHON_VERSION}")"
    (cd "${REPO_ROOT}/mnemosyne-core" && \
        PATH="$(dirname "${py_bin}"):$PATH" maturin build --release --interpreter "${py_bin}" --strip)
    log "rust extension wheel built under ${WHEELS_DIR}"
}

build_dependency_venv() {
    log "creating runtime-deps venv at ${VENV_DIR} (python${PYTHON_VERSION})"
    local py_bin
    py_bin="$(command -v python${PYTHON_VERSION} || uv python find "${PYTHON_VERSION}")"
    rm -rf "${VENV_DIR}"
    "${py_bin}" -m venv "${VENV_DIR}"
    local pip_bin="${VENV_DIR}/bin/pip"
    # Pin to CPython-friendly deps. --no-deps is OFF so transitive closure ships.
    "${pip_bin}" install --quiet --upgrade pip
    "${pip_bin}" install --quiet -r "${REPO_ROOT}/requirements-binary.txt"
    log "venv populated ($(ls "${VENV_DIR}/lib/python${PYTHON_VERSION}/site-packages" | wc -l) top-level packages)"

    # Generate fs_files.star enumerating data files of FILESYSTEM_PACKAGES.
    # These packages use importlib.resources.files().iterdir() at runtime,
    # which PyOxidizer's frozen importer cannot serve; we ship them as
    # filesystem-relative files alongside the binary instead.
    local sp="${VENV_DIR}/lib/python${PYTHON_VERSION}/site-packages"
    local star="${VENV_DIR}/fs_files.star"
    {
        printf '# AUTO-GENERATED by scripts/build_binary.sh — do not edit.\n'
        printf '# Lists data files of FILESYSTEM_PACKAGES for make_install.\n'
        printf '# Paths are absolute; strip_prefix in pyoxidizer.bzl must match.\n'
        printf 'FS_FILES = [\n'
        for pkg in jsonschema_specifications referencing; do
            pkgdir="${sp}/${pkg}"
            [[ -d "${pkgdir}" ]] || continue
            while IFS= read -r -d '' f; do
                # Skip __pycache__ and tests/ subdirs.
                case "$f" in
                    *__pycache__*|*/tests/*) continue ;;
                esac
                printf '    "%s",\n' "$f"
            done < <(find "${pkgdir}" -type f -print0)
        done
        printf ']\n'
    } > "${star}"
    # Also write the strip prefix so pyoxidizer.bzl can read it via load().
    cat > "${VENV_DIR}/fs_prefix.star" <<EOF
# AUTO-GENERATED — strip_prefix matching FS_FILES absolute paths.
FS_STRIP_PREFIX = "${sp}/"
EOF
    log "fs_files.star generated ($(grep -c '    "' "${star}") files, prefix ${sp}/)"
}

run_pyoxidizer() {
    local mode_arg=()
    # PyOxidizer 0.24 defaults to debug builds. Pass --release for release.
    if [[ "${BUILD_MODE}" == "release" ]]; then
        mode_arg=(--release)
    fi
    log "pyoxidizer build (target: x86_64-unknown-linux-gnu, mode: ${BUILD_MODE})"
    (cd "${REPO_ROOT}" && \
        pyoxidizer build --target-triple x86_64-unknown-linux-gnu "${mode_arg[@]}")
}

install_binary() {
    local src
    src="${REPO_ROOT}/build/x86_64-unknown-linux-gnu/${BUILD_MODE}/install/mnemosyne"
    if [[ ! -f "${src}" ]]; then
        # PyOxidizer may produce under release/ even when requested as default.
        src="${REPO_ROOT}/build/x86_64-unknown-linux-gnu/release/install/mnemosyne"
    fi
    if [[ ! -f "${src}" ]]; then
        err "pyoxidizer did not produce a binary under build/x86_64-unknown-linux-gnu/*/install/"
        return 1
    fi
    mkdir -p "${BUILD_DIR}"
    # Copy the binary + the filesystem-relative lib/ dir + FILESYSTEM_PACKAGES.
    cp -f "${src}" "${BUILD_DIR}/mnemosyne"
    local src_install
    src_install="$(dirname "${src}")"
    # lib/ contains extension modules (.so) extracted by the filesystem fallback.
    if [[ -d "${src_install}/lib" ]]; then
        rm -rf "${BUILD_DIR}/lib"
        cp -r "${src_install}/lib" "${BUILD_DIR}/lib"
    fi
    # FILESYSTEM_PACKAGES directories (jsonschema_specifications, referencing).
    for pkg in jsonschema_specifications referencing; do
        if [[ -d "${src_install}/${pkg}" ]]; then
            rm -rf "${BUILD_DIR}/${pkg}"
            cp -r "${src_install}/${pkg}" "${BUILD_DIR}/${pkg}"
        fi
    done
    chmod +x "${BUILD_DIR}/mnemosyne"
    # strip-all removes debug symbols + symbol tables (smaller than strip-debug).
    # AC6 (reclassified advisory, see PM Amendment in ISSUE-0008): PyOxidizer
    # 0.24 + CPython 3.10 + required deps land well over 100MB; the budget is
    # owned by ISSUE-0009 (PyOxidizer 0.4x + CPython 3.12 upgrade).
    strip --strip-all "${BUILD_DIR}/mnemosyne" || strip --strip-debug "${BUILD_DIR}/mnemosyne" || log "warning: strip failed (non-fatal)"
    # Strip lib/**/*.so as well — these ship unstripped from PyOxidizer and
    # account for ~9MB of the lib/ footprint. Falls back to --strip-debug for
    # any .so that rejects --strip-all (some extension modules do).
    local so_count=0 strip_fail=0
    while IFS= read -r -d '' so; do
        so_count=$((so_count + 1))
        if ! strip --strip-all "${so}" 2>/dev/null && ! strip --strip-debug "${so}" 2>/dev/null; then
            strip_fail=$((strip_fail + 1))
        fi
    done < <(find "${BUILD_DIR}/lib" -type f -name '*.so' -print0 2>/dev/null)
    log "stripped ${so_count} .so files in lib/ (${strip_fail} failed)"
    local binary_bytes binary_mb
    binary_bytes="$(stat -c %s "${BUILD_DIR}/mnemosyne")"
    binary_mb="$(awk -v b="${binary_bytes}" 'BEGIN{printf "%.1f", b/1024/1024}')"
    # Full distribution footprint: binary + lib/ + filesystem-shipped companion
    # dirs (jsonschema_specifications, referencing). PyOxidizer 0.24 cannot
    # collapse these into the binary proper — the path forward is ISSUE-0009.
    local lib_bytes companion_bytes dist_bytes dist_mb
    lib_bytes="$(du -sb "${BUILD_DIR}/lib" 2>/dev/null | cut -f1)"
    companion_bytes=0
    for pkg in jsonschema_specifications referencing; do
        [[ -d "${BUILD_DIR}/${pkg}" ]] && companion_bytes=$((companion_bytes + $(du -sb "${BUILD_DIR}/${pkg}" | cut -f1)))
    done
    dist_bytes=$((binary_bytes + lib_bytes + companion_bytes))
    dist_mb="$(awk -v b="${dist_bytes}" 'BEGIN{printf "%.1f", b/1024/1024}')"
    log "binary ready: ${BUILD_DIR}/mnemosyne (${binary_mb} MB, ${binary_bytes} bytes)"
    log "distribution footprint: ${dist_mb} MB (binary ${binary_mb} MB + lib $(awk -v b="${lib_bytes}" 'BEGIN{printf "%.1f", b/1024/1024}') MB + companion $(awk -v b="${companion_bytes}" 'BEGIN{printf "%.1f", b/1024/1024}') MB)"
    # AC6 reclassified advisory (PM Amendment in ISSUE-0008): the full
    # distribution footprint on PyOxidizer 0.24 + CPython 3.10 + the required
    # runtime dep set (cryptography alone is ~11MB stripped in lib/) is over
    # the 100MB budget. The path to <=100MB is the PyOxidizer 0.4x upgrade
    # (ISSUE-0009). We log the measurement rather than failing the build.
    if (( dist_bytes > 100 * 1024 * 1024 )); then
        log "NOTE: AC6 advisory — distribution is ${dist_mb} MB (over 100 MB; owned by ISSUE-0009 PyOxidizer 0.4x upgrade; see BINARY_BUILD.md)"
    fi
}

main() {
    case "${1:-build}" in
        --check)
            check_toolchain
            ;;
        --debug)
            BUILD_MODE="debug"
            check_toolchain
            build_rust_extension
            build_dependency_venv
            run_pyoxidizer
            install_binary
            ;;
        build|"")
            check_toolchain
            build_rust_extension
            build_dependency_venv
            run_pyoxidizer
            install_binary
            ;;
        *)
            err "unknown argument: $1 (expected: --check | build | --debug)"
            exit 2
            ;;
    esac
}

main "$@"
