.TH MNEMOSYNE-GRAPH-QUERY 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne graph-query \- Query the knowledge graph using structured expressions.
.SH SYNOPSIS
\fBmnemosyne graph-query\fR [options]
.SH DESCRIPTION
Query the knowledge graph using structured expressions.
.SH OPTIONS
.TP
\fBquery\fR
Query expression (see syntax below)
.TP
\fB\-\-query\fR
Query expression (alias of positional)
.TP
\fB\-\-stats\fR
Show graph statistics as JSON
.TP
\fB\-\-project\fR
Query a specific project by name
.TP
\fB\-\-global\fR
Search across all projects (ignore auto\-scope)
.TP
\fB\-\-examples\fR
Show query syntax and examples
.SH SEE ALSO
mnemosyne(1)
