.TH MNEMOSYNE-GRAPH-STATS 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne graph-stats \- Show graph statistics as JSON.
.SH SYNOPSIS
\fBmnemosyne graph-stats\fR [options]
.SH DESCRIPTION
Show graph statistics as JSON.
.SH OPTIONS
\fB-h, --help\fR
Show this help and exit.
.SH SEE ALSO
mnemosyne(1)
