.TH MNEMOSYNE-PROJECT-SHOW 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne project-show \- Show project details and entity counts.
.SH SYNOPSIS
\fBmnemosyne project-show\fR [options]
.SH DESCRIPTION
Show project details and entity counts.
.SH OPTIONS
.TP
\fBidentifier\fR
Project name or hash (default: current project)
.SH SEE ALSO
mnemosyne(1)
