.TH MNEMOSYNE-PROJECT-UNREGISTER 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne project-unregister \- Remove project registration (does not delete entities).
.SH SYNOPSIS
\fBmnemosyne project-unregister\fR [options]
.SH DESCRIPTION
Remove project registration (does not delete entities).
.SH OPTIONS
.TP
\fBidentifier\fR
Project name or hash
.SH SEE ALSO
mnemosyne(1)
