.TH MNEMOSYNE-PROJECT-LIST 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne project-list \- List all registered projects.
.SH SYNOPSIS
\fBmnemosyne project-list\fR [options]
.SH DESCRIPTION
List all registered projects.
.SH OPTIONS
\fB-h, --help\fR
Show this help and exit.
.SH SEE ALSO
mnemosyne(1)
