.TH MNEMOSYNE-GRAPH-PATH 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne graph-path \- Find shortest path between two entities (path:FROM,TO DSL shortcut).
.SH SYNOPSIS
\fBmnemosyne graph-path\fR [options]
.SH DESCRIPTION
Find shortest path between two entities (path:FROM,TO DSL shortcut).
.SH OPTIONS
.TP
\fBfrom_entity\fR
Starting entity
.TP
\fBto_entity\fR
Ending entity
.SH SEE ALSO
mnemosyne(1)
