.TH MNEMOSYNE-GRAPH-SEARCH 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne graph-search \- Fuzzy search across all entities (search:TERM DSL shortcut).
.SH SYNOPSIS
\fBmnemosyne graph-search\fR [options]
.SH DESCRIPTION
Fuzzy search across all entities (search:TERM DSL shortcut).
.SH OPTIONS
.TP
\fBterm\fR
Search term
.SH SEE ALSO
mnemosyne(1)
