.TH MNEMOSYNE-PROJECT-REGISTER 1 "2026-06-23" "mnemosyne" "Mnemosyne CLI"
.SH NAME
mnemosyne project-register \- Manually register a project path.
.SH SYNOPSIS
\fBmnemosyne project-register\fR [options]
.SH DESCRIPTION
Manually register a project path.
.SH OPTIONS
.TP
\fBpath\fR
Path to project root
.TP
\fB\-\-name\fR
Project name (default: directory basename)
.SH SEE ALSO
mnemosyne(1)
